"""
Build a SAP CPI-importable ZIP for a single iFlow artifact.

ZIP structure (files at root — NO wrapper folder) confirmed from live tenant iFlows:
  .project
  metainfo.prop
  META-INF/MANIFEST.MF                        ← LF line endings (NOT CRLF)
  src/main/resources/parameters.prop
  src/main/resources/parameters.propdef
  src/main/resources/scenarioflows/integrationflow/<id>.iflw
  src/main/resources/script/<name>.groovy     ← optional, one per Groovy step
  src/main/resources/mapping/<name>.mmap      ← optional
  src/main/resources/wsdl/<name>.xsd          ← optional
"""

import io
import re
import zipfile
from typing import Optional


def _safe_id(name: str) -> str:
    """Convert a display name to a safe bundle symbolic name (alphanumeric + _ -)."""
    s = re.sub(r"[^A-Za-z0-9_\-]", "_", name.strip())
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "MyIFlow"


def _extract_params(iflw_xml: str) -> list[str]:
    """
    Extract {{PARAM_NAME}} placeholders from the iFlw XML in order of appearance.
    Skips the built-in {{Scheduler}} timer placeholder.
    """
    params = re.findall(r'\{\{([^}]+)\}\}', iflw_xml)
    seen: list[str] = []
    for p in params:
        p = p.strip()
        if p and p != "Scheduler" and p not in seen:
            seen.append(p)
    return seen


def build_iflow_zip(
    iflow_xml: str,
    name: str,
    description: str = "",
    version: str = "1.0.0",
    scripts: Optional[dict[str, str]] = None,
    mmaps: Optional[dict[str, str]] = None,
    xsds: Optional[dict[str, str]] = None,
) -> bytes:
    """
    Package *iflow_xml* into a SAP CPI-importable ZIP.

    Parameters
    ----------
    iflow_xml  : The .iflw XML string generated by the AI.
    name       : iFlow display name (also used as bundle symbolic name).
    description: One-line description written into metainfo.prop.
    version    : Bundle version string, e.g. "1.0.0".
    scripts    : dict of {filename: groovy_source} for Groovy script steps.
    mmaps      : dict of {filename: mmap_xml} for message mapping artifacts.
    xsds       : dict of {filename: xsd_content} for schema files.

    Returns raw ZIP bytes ready to be streamed as a download.
    """
    iflow_id = _safe_id(name)
    desc = description.strip() or f"Integration flow: {name}"
    scripts = scripts or {}
    mmaps   = mmaps   or {}
    xsds    = xsds    or {}

    # Auto-extract parameters from {{PARAM_NAME}} placeholders in the iFlw XML
    params = _extract_params(iflow_xml)

    # ── MANIFEST.MF ──────────────────────────────────────────────────────────
    # IMPORTANT: CRLF line endings (\r\n) — confirmed from real CPI iFlow exports.
    # Field order must match CPI's export format. Import-Package is required for
    # the OSGi bundle loader to resolve the Groovy runtime and CPI message API.
    manifest = (
        "Manifest-Version: 1.0\r\n"
        "Bundle-ManifestVersion: 2\r\n"
        f"Bundle-Name: {iflow_id}\r\n"
        f"Bundle-SymbolicName: {iflow_id}\r\n"
        f"Bundle-Version: {version}\r\n"
        "SAP-BundleType: IntegrationFlow\r\n"
        "SAP-NodeType: IFLMAP\r\n"
        "SAP-RuntimeProfile: iflmap\r\n"
        "Import-Package: com.sap.gateway.ip.core.customdev.util,java.io,java.text,\r\n"
        " java.util,org.apache.camel;version=\"2.8\",org.apache.camel.builder;versio\r\n"
        " n=\"2.8\",org.apache.camel.model;version=\"2.8\",org.apache.camel.processor\r\n"
        " ;version=\"2.8\",org.osgi.framework;version=\"1.6.0\"\r\n"
        f"Origin-Bundle-Name: {iflow_id}\r\n"
        f"Origin-Bundle-SymbolicName: {iflow_id}\r\n"
        "\r\n"   # trailing blank CRLF line is required by JAR spec
    )

    # ── metainfo.prop ─────────────────────────────────────────────────────────
    # ONLY comment + description line. Never use bundle keys here.
    metainfo = f"#Store metainfo properties\ndescription={desc}\n"

    # ── .project ──────────────────────────────────────────────────────────────
    project = (
        '<?xml version="1.0" encoding="UTF-8"?><projectDescription>\n'
        f'   <name>{iflow_id}</name>\n'
        '   <comment/>\n'
        '   <projects/>\n'
        '   <buildSpec>\n'
        '      <buildCommand>\n'
        '         <name>org.eclipse.jdt.core.javabuilder</name>\n'
        '         <arguments/>\n'
        '      </buildCommand>\n'
        '   </buildSpec>\n'
        '   <natures>\n'
        '      <nature>org.eclipse.jdt.core.javanature</nature>\n'
        '      <nature>com.sap.ide.ifl.project.support.project.nature</nature>\n'
        '      <nature>com.sap.ide.ifl.bsn</nature>\n'
        '   </natures>\n'
        '</projectDescription>'
    )

    # ── parameters.prop ───────────────────────────────────────────────────────
    prop_lines = ["#", f"#Parameters for {iflow_id}"]
    for p in params:
        prop_lines.append(f"{p}=")
    parameters_prop = "\n".join(prop_lines) + "\n"

    # ── parameters.propdef ────────────────────────────────────────────────────
    # root element = <parameters> with standalone="no"
    param_defs = ""
    for p in params:
        human = p.replace("_", " ").title()
        param_defs += (
            "<parameter>\n"
            "    <key/>\n"
            f"    <name>{p}</name>\n"
            "    <type>xsd:string</type>\n"
            "    <isRequired>true</isRequired>\n"
            "    <constraint/>\n"
            f"    <description>{human}</description>\n"
            "    <additionalMetadata/>\n"
            "  </parameter>"
        )
    parameters_propdef = (
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>'
        f"<parameters>{param_defs}<param_references/></parameters>\n"
    )

    # ── Assemble ZIP in memory ────────────────────────────────────────────────
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Root-level files (NO wrapper folder)
        zf.writestr(".project",     project)
        zf.writestr("metainfo.prop", metainfo)
        zf.writestr("META-INF/MANIFEST.MF", manifest)

        # src/main/resources
        zf.writestr("src/main/resources/parameters.prop",    parameters_prop)
        zf.writestr("src/main/resources/parameters.propdef", parameters_propdef)

        # The iFlow definition
        zf.writestr(
            f"src/main/resources/scenarioflows/integrationflow/{iflow_id}.iflw",
            iflow_xml,
        )

        # Optional Groovy scripts
        for fname, content in scripts.items():
            if not fname.endswith(".groovy"):
                fname += ".groovy"
            zf.writestr(f"src/main/resources/script/{fname}", content)

        # Optional message mapping artifacts
        for fname, content in mmaps.items():
            zf.writestr(f"src/main/resources/mapping/{fname}", content)

        # Optional XSD/WSDL schemas
        for fname, content in xsds.items():
            folder = "xsd" if fname.endswith(".xsd") else "wsdl"
            zf.writestr(f"src/main/resources/{folder}/{fname}", content)

    return buf.getvalue()
